sonar.projectKey=violalala123_python-project-50
sonar.organization=violalala123

# Где лежит код и тесты
sonar.sources=gendiff
sonar.tests=tests
sonar.python.version=3.12

# Путь к отчету о покрытии
sonar.python.coverage.reportPaths=coverage.xml